### ISSUE TITLE
0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

### ISSUE THREAD

**Issue by lowellran** [juzeon/SydneyQt#101] opened 2023-09-18 08:29 UTC
佬，这是什么原因。cookie checker确实能检测我账号名字，cloudflare也搭建了。raise TooManyRedirects(
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://edgeservices.bing.com/edgesvc/turing/conversation/create')

**Comment by juzeon** [comment] 2023-09-18 08:38
Duplicate of #98

**Closed by juzeon** 2023-09-18 08:38 UTC

**Comment by lowellran** [comment] 2023-09-18 09:34
谢谢，佬
